import { UIConfig } from "../types/uiConfig";

export const defaultUIConfig: UIConfig = {
  navbar: {
    hideCarLoan: false,
    hideUsedCarLoan: false,
    hideTwoWheelerLoan: false,
    hideGoldLoan: false,
    hideBusinessLoans: false,
    hideHomeLoan: false,
    hideLoanAgainstProperty: false,
    hideCreditCard: false,
    hideLoanIntelligence: false,
    hideMyPortfolio: false,
    hideAllTabs: false,
    educationLoan: {
      hideUnionBankOfIndia: false,
      hideAxisBank: false,
      hideICICIBank: false,
      hideIDFCFirstBank: false,
      hideCredilaHDFC: false,
      hideAvanse: false,
      hideInCred: false,
      hideProdigyFinance: false,
      hideMpowerFinance: false,
      hideStateBankOfIndia: false,
      hideBankOfBaroda: false,
    },
    personalLoan: {
      hideHDFCBank: false,
      hideICICIBank: false,
      hideStateBankOfIndia: false,
      hideAxisBank: false,
      hideKotakMahindraBank: false,
      hideBajajFinserv: false,
      hideTataCapital: false,
      hideIndusIndBank: false,
      hideYesBank: false,
      hidePunjabNationalBank: false,
    },
  },
  sections: {
    hidePartnerStats: false,
    hideWallOfWin: false,
    hideBankingEcosystem: false,
    hideStatsSection: false,
    hideCreditCardSection: false,
    hideFooterCarLoan: false,
    hideFooterTwoWheelerLoan: false,
    hideFooterBusinessLoan: false,
    hideFooterGoldLoan: false,
    hideFooterCreditCard: false,
    hideAboutUsCompanyStats: false,
    hideAboutUsStats: false,
    hideAboutUsFounders: false,
    hideAboutUsAdvisors: false,
    hideAboutUsInvestors: false,
    hideAboutUsPress: false,
    hideCareersSalaryPerk: false,
    hideProductCarLoan: false,
    hideProductUsedCarLoan: false,
    hideProductTwoWheelerLoan: false,
    hideProductGoldLoan: false,
    hideProductBusinessLoan: false,
    hideProductMicroLoan: false,
    hideAllFooterLinks: false,
    hideCreduAi: false,
    hideHeroCtas: false,
    hideCreditScoreForm: false,
    hideFooterBottomLinks: false,
  },
};
