import { UIConfig } from "../types/uiConfig";

export const defaultUIConfig: UIConfig = {
  navbar: {
    hideCarLoan: false,
    hideUsedCarLoan: false,
    hideTwoWheelerLoan: false,
    hideGoldLoan: false,
    hideBusinessLoans: false,
    hideHomeLoan: false,
    hideLoanAgainstProperty: false,
    hideAllTabs: false,
  },
  sections: {
    hidePartnerStats: false,
    hideWallOfWin: false,
    hideBankingEcosystem: false,
    hideStatsSection: false,
    hideFooterCarLoan: false,
    hideFooterTwoWheelerLoan: false,
    hideFooterBusinessLoan: false,
    hideFooterGoldLoan: false,
    hideAboutUsCompanyStats: false,
    hideAboutUsStats: false,
    hideAboutUsFounders: false,
    hideAboutUsAdvisors: false,
    hideAboutUsInvestors: false,
    hideAboutUsPress: false,
    hideCareersSalaryPerk: false,
    hideProductCarLoan: false,
    hideProductUsedCarLoan: false,
    hideProductTwoWheelerLoan: false,
    hideProductGoldLoan: false,
    hideProductBusinessLoan: false,
    hideProductMicroLoan: false,
    hideAllFooterLinks: false,
    hideCreduAi: false,
    hideHeroCtas: false,
    hideCreditScoreForm: false,
    hideFooterBottomLinks: false,
  },
};
